"""SQLAlchemy models. Importing this package registers every table on Base.metadata."""
from app.models import (  # noqa: F401
    ai_governance,
    client_experience,
    compliance,
    compliance_program,
    composites,
    connectors,
    corporate_actions,
    crm,
    engagement,
    governance,
    graph,
    identity,
    knowledge,
    onboarding,
    portfolio,
    skill,
    sleeves,
    telemetry,
    tenant,
    thread,
    trading,
    vault,
)
